languageCode = "es"
languageName = "Español"
displayName = "🇪🇸"
htmlCode = "es"
weight = 2
rtl = false
title = "Jorge Carpio"
description = "Página personal de Jorge Carpio"
dateFormat = "2 Jan 2006"

[author]
    name = "Jorge Carpio"
    image = "img/author.jpg"
    headline = "Platform Engineer"
    bio = "Programo, toco música y subo montañas"
    links = [
        { email = "mailto:carpioldc@gmail.com" },
        #   { link = "https://link-to-some-website.com/" },
        #   { codepen = "https://codepen.io/username" },
        #   { dev = "https://dev.to/username" },
        #   { discord = "https://discord.gg/invitecode" },
        #   { dribbble = "https://dribbble.com/username" },
        #   { facebook = "https://facebook.com/username" },
        #   { foursquare = "https://foursquare.com/username" },
        { github = "https://github.com/ibice" },
        #   { gitlab = "https://gitlab.com/carpioldc" },
        #   { keybase = "https://keybase.io/username" },
        #   { lastfm = "https://lastfm.com/user/username" },
        { linkedin = "https://linkedin.com/in/jorge-carpio" },
        #   { mastodon = "https://mastodon.instance/@username" },
        #   { medium = "https://medium.com/username" },
        #   { pinterest = "https://pinterest.com/username" },
        #   { reddit = "https://reddit.com/user/username" },
        #   { slack = "https://workspace.url/team/userid" },
        #   { snapchat = "https://snapchat.com/add/username" },
        #   { soundcloud = "https://soundcloud.com/username" },
        #   { steam = "https://steamcommunity.com/profiles/userid" },
        #   { tiktok = "https://tiktok.com/@username" },
        #   { twitch = "https://twitch.tv/username" },
        #   { twitter = "https://twitter.com/username" },
        #   { youtube = "https://www.youtube.com/@jcarpio" },
    ]
